// GET DATA
export const GET_ALL_DATA = "GET_ALL_DATA";
export const GET_DATA_BY_NAME = "GET_DATA_BY_NAME";
export const GET_DETAIL_COUNTRY = "GET_DETAIL_COUNTRY";
export const GET_DETAIL_RESET = "GET_DETAIL_RESET";
// ORDER
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";
//FILTERS
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
